[package]
name = "flare3d-example"
version = "0.1.0"
edition = "2021"
authors = ["KrLite"]
description = "Example of Flare3d"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = ["game-development"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
flare3d = { path = "../" }
winit = "0.29"
wgpu = "0.19"
futures-executor = "0.3"

[target.'cfg(target_os = "macos")'.dependencies]
display-link = { git = "https://github.com/BrainiumLLC/display-link" }
