[package]
name = "rimecraft-render-math"
version = "0.1.0"
edition = "2024"
authors = ["KrLite"]
description = "Render math library for Rimecraft"
repository = "https://codeberg.org/DM-Earth/rimecraft/"
license = "AGPL-3.0-or-later"
categories = ["game-development"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
glam = "0.30"
num-traits = "0.2"

[features]

[lints]
workspace = true
