[package]
name = "rimecraft-render"
version = "0.1.0"
edition = "2024"
authors = ["KrLite"]
description = "Minecraft rendering API"
repository = "https://codeberg.org/DM-Earth/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
rimecraft-global-cx = { path = "../global-cx" }
rimecraft-local-cx = { path = "../local-cx" }
rimecraft-render-math = { path = "../../util/render-math" }
glam = "0.30"

[lints]
workspace = true
