[package]
name = "rimecraft-window"
version = "0.1.0"
edition = "2024"
authors = ["KrLite"]
description = "Window management for Rimecraft"
repository = "https://codeberg.org/DM-Earth/rimecraft/"
license = "AGPL-3.0-or-later"
categories = ["game-development"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
rimecraft-global-cx = { path = "../../core/global-cx" }
rimecraft-local-cx = { path = "../../core/local-cx" }
glam = "0.30"
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = []
serde = ["dep:serde"]

[lints]
workspace = true
